# Generated by Django 4.2.3 on 2023-07-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="todo_app",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                ("head", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=400)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
